HamburgerMenuProject/Models/Entities/Hamburger.cs
using HamburgerMenuProject.Models.BaseEntities;

namespace HamburgerMenuProject.Models.Entities
{
    public class Hamburger : BaseEntity
    {       
        
    }
}

HamburgerMenuProject/Areas/Admin/Controllers/HamburgerController.cs
using HamburgerMenuProject.Models;
using HamburgerMenuProject.Models.Entities;
using HamburgerMenuProject.Repository.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HamburgerMenuProject.Controllers
{
    [Authorize(Roles ="Admin")]
    public class HamburgerController : Controller
    {
        private readonly IRepository<Hamburger> hamburgerRepository;

        public HamburgerController(IRepository<Hamburger> hamburgerRepository)
        {
            this.hamburgerRepository = hamburgerRepository;
        }
        public ActionResult Index()
        {
            var hamburgerList = hamburgerRepository.GetAll().ToList();
            return View(hamburgerList);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Hamburger hamburger,IFormFile formFile)
        {
            hamburgerRepository.AddPhoto(hamburger, formFile);
            hamburgerRepository.Add(hamburger);
            return RedirectToAction("Index");
        }

        public ActionResult Update(int id)
        {
            var hamburger = hamburgerRepository.GetById(id);
            return View(hamburger);
        }

        [HttpPost]        
        public ActionResult Update(Hamburger hamburger, IFormFile formFile)
        {
            var Hamburger = hamburgerRepository.GetById(hamburger.ID);
            if (formFile != null)
            {
                hamburgerRepository.AddPhoto(Hamburger, formFile);
            }
            Hamburger.Name = hamburger.Name;
            Hamburger.Price = hamburger.Price;
            Hamburger.IsActive = hamburger.IsActive;
            hamburgerRepository.Update(Hamburger);
            return RedirectToAction("Index");
        }

              
        public ActionResult Delete(int id)
        {
            var hamburger = hamburgerRepository.GetById(id);
            hamburgerRepository.Delete(hamburger);
            return RedirectToAction("Index");
        }
    }
}

HamburgerMenuProject/Areas/Admin/Views/Hamburger/Create.cshtml
@using HamburgerMenuProject.Models.Entities;

@model Hamburger
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Hamburger" method="post" enctype="multipart/form-data">
            <div class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <input asp-for="Photo" class="form-control" type="File" name="formFile"/>
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

HamburgerMenuProject/Areas/Admin/Views/Hamburger/Index.cshtml
@using HamburgerMenuProject.Models.Entities;

@model List<Hamburger>
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<p>
    <a asp-action="Create" class="btn btn-primary">Add New Hamburger</a>
</p>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                Photo
            </th>
            <th>
                IsActive
            </th>
            <th>
                Name
            </th>            
            <th>
                Created Time
            </th>
            <th>
                Price
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (Hamburger item in Model)
        {
            <tr>
                <td>
                    <img src="/images/@item.Photo" width="150" height="150" />
                </td>
                <td>
                    @item.IsActive
                </td>
                <td>
                    @item.Name
                </td>                
                <td>
                    @item.CreatedTime.ToString("dd/MM/yyyyy")
                </td>
                <td>
                    @item.Price
                </td>
                <td>
                    <a class="btn btn-warning" asp-action="Update" asp-route-id="@item.ID">Update </a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.ID">Delete </a>
                </td>
            </tr>
        }
    </tbody>

</table>

HamburgerMenuProject/Areas/Admin/Views/Hamburger/Update.cshtml
@using HamburgerMenuProject.Models.Entities;
@model Hamburger
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Update" method="post">
            <input type="hidden" asp-for="ID"/>
            <div class="text-danger"></div>
            <img src="/images/@Model.Photo" width="150" height="150" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="IsActive" class="control-label"></label>
                <select asp-for="IsActive" class="form-control">
                    <option value="true">True</option>
                    <option value="False">False</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <input asp-for="Photo" class="form-control" type="File" name="formFile" />
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>