HamburgerMenuProject/Areas/Admin/Controllers/DessertController.cs
using HamburgerMenuProject.Models;
using HamburgerMenuProject.Models.Entities;
using HamburgerMenuProject.Repository.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace HamburgerMenuProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DessertController : Controller
    {
        private readonly IRepository<Dessert> dessertrepository;

        public DessertController(IRepository<Dessert> dessertrepository)
        {
            this.dessertrepository = dessertrepository;
        }
        public IActionResult Index()
        {
            var dessertList = dessertrepository.GetAll().ToList();
            return View(dessertList);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Dessert dessert, IFormFile formFile)
        {
            dessertrepository.AddPhoto(dessert, formFile);
            dessertrepository.Add(dessert);
            return RedirectToAction("Index");

        }

        public ActionResult Update(int id)
        {
            var dessert = dessertrepository.GetById(id);
            return View(dessert);
        }

        [HttpPost]
        public ActionResult Update(Dessert dessert,IFormFile formFile)
        {
            var Dessert = dessertrepository.GetById(dessert.ID);
            if (formFile !=null)
            {
                
                dessertrepository.AddPhoto(Dessert, formFile);
            }
            Dessert.Name = dessert.Name;
            Dessert.Price = dessert.Price;
            Dessert.IsActive = dessert.IsActive;
            dessertrepository.Update(Dessert);
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int id)
        {
            var dessert = dessertrepository.GetById(id);
            dessertrepository.Delete(dessert);
            return RedirectToAction("Index");
        }
    }
}

HamburgerMenuProject/Areas/Admin/Controllers/DrinkController.cs
using HamburgerMenuProject.Models;
using HamburgerMenuProject.Models.Entities;
using HamburgerMenuProject.Models.Enums;
using HamburgerMenuProject.Repository.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Data;

namespace HamburgerMenuProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DrinkController : Controller
    {
        private readonly IRepository<Drink> drinkrepository;

        public DrinkController(IRepository<Drink> drinkrepository)
        {
            this.drinkrepository = drinkrepository;
        }
        public IActionResult Index()
        {
            var drinkList = drinkrepository.GetAll().ToList();
            return View(drinkList);
        }
       
        public ActionResult Create()
        {
            var enumList = Enum.GetValues(typeof(Size)).Cast<Size>().ToList();
            SelectList selectList = new SelectList(enumList);
            ViewBag.size = selectList;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Drink drink, IFormFile formFile)
        {
            drinkrepository.AddPhoto(drink, formFile);
            drinkrepository.Add(drink);
            return RedirectToAction("Index");

        }

        public ActionResult Update(int id)
        {
            var drink = drinkrepository.GetById(id);
            return View(drink);
        }

        [HttpPost]
        public ActionResult Update(Drink drink,IFormFile formFile)
        {
            var Drink = drinkrepository.GetById(drink.ID);
            if (formFile != null)
            {
                drinkrepository.AddPhoto(Drink, formFile);
            }
            Drink.Name = drink.Name;
            Drink.Price = drink.Price;
            Drink.IsActive = drink.IsActive;
            drinkrepository.Update(Drink);
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int id)
        {
            var drink = drinkrepository.GetById(id);
            drinkrepository.Delete(drink);
            return RedirectToAction("Index");
        }
    }
}

HamburgerMenuProject/Areas/Admin/Controllers/FriesController.cs
using HamburgerMenuProject.Models;
using HamburgerMenuProject.Models.Entities;
using HamburgerMenuProject.Repository.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace HamburgerMenuProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FriesController : Controller
    {
        private readonly IRepository<Fries> friesRepository;

        public FriesController(IRepository<Fries> friesRepository)
        {
            this.friesRepository = friesRepository;
        }
        public IActionResult Index()
        {
            var friesList = friesRepository.GetAll().ToList();
            return View(friesList);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Fries fries,IFormFile formFile)
        {
            friesRepository.AddPhoto(fries, formFile);
            friesRepository.Add(fries);
            return RedirectToAction("Index");

        }
        public ActionResult Update(int id)
        {
            var fries = friesRepository.GetById(id);
            return View(fries);
        }

        [HttpPost]
        public ActionResult Update(Fries fries,IFormFile formFile)
        {
            var Fries = friesRepository.GetById(fries.ID);
            if (formFile != null)
            {
                friesRepository.AddPhoto(Fries, formFile);
            }
            Fries.Name = fries.Name;
            Fries.Price = fries.Price;
            Fries.IsActive = fries.IsActive;
            friesRepository.Update(Fries);
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int id)
        {
            var fries = friesRepository.GetById(id);
            friesRepository.Delete(fries);
            return RedirectToAction("Index");
        }
    }
}

HamburgerMenuProject/Areas/Admin/Controllers/SauceController.cs
using HamburgerMenuProject.Models;
using HamburgerMenuProject.Models.Entities;
using HamburgerMenuProject.Repository.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace HamburgerMenuProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SauceController : Controller
    {
        private readonly IRepository<Sauce> sauceRepository;

        public SauceController(IRepository<Sauce> sauceRepository)
        {
            this.sauceRepository = sauceRepository;
        }
        public IActionResult Index()
        {
            var sauceList = sauceRepository.GetAll().ToList();
            return View(sauceList);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Sauce sauce, IFormFile formFile)
        {
            sauceRepository.AddPhoto(sauce, formFile);
            sauceRepository.Add(sauce);
            return RedirectToAction("Index");

        }

        public ActionResult Update(int id)
        {
            var sauce = sauceRepository.GetById(id);
            return View(sauce);
        }

        [HttpPost]
        public ActionResult Update(Sauce sauce,IFormFile formFile)
        {
            var Sauce = sauceRepository.GetById(sauce.ID);
            if (formFile !=null)
            {
                sauceRepository.AddPhoto(Sauce, formFile);
            }
            Sauce.Name = sauce.Name;
            Sauce.Price = sauce.Price;
            Sauce.IsActive = sauce.IsActive;
            sauceRepository.Update(Sauce);
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int id)
        {
            var sauce = sauceRepository.GetById(id);
            sauceRepository.Delete(sauce);
            return RedirectToAction("Index");
        }
    }
}

HamburgerMenuProject/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using HamburgerMenuProject.Models.User;
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<AppUser> signInManager;
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- FontAwesome 4.3.0 -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons 2.0.0 -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="~/Content/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="~/Content/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="~/Content/plugins/iCheck/flat/blue.css" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="~/Content/plugins/morris/morris.css" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="~/Content/plugins/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
    <!-- Date Picker -->
    <link href="~/Content/plugins/datepicker/datepicker3.css" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="~/Content/plugins/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
    <!-- bootstrap wysihtml5 - text editor -->
    <link href="~/Content/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" type="text/css" />
    
</head>
<body class="skin-blue">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <b class="logo">@Html.ActionLink("Control Panel", "Index", "AdminHome")</b>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>                

            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">                    
                    <div class="pull-left info">
                        <p>@User.Identity.Name</p>

                        <a href="#"><i class="fa fa-circle text-success"></i>Online</a>
                    </div>
                </div>

                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header">MAIN NAVIGATION</li>
                    <li class="active treeview">
                        <a href="/Admin/AdminHome/Index">
                            <i class="fa fa-home"></i> <span>Home</span>
                        </a>

                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-table"></i>
                            <span>Products</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a asp-action="Index" asp-controller="Hamburger"><i class="fa fa-circle-o"></i> Hamburgers</a></li>
                            <li><a asp-action="Index" asp-controller="Drink"><i class="fa fa-circle-o"></i> Drinks</a></li>
                            <li><a asp-action="Index" asp-controller="Dessert"><i class="fa fa-circle-o"></i> Desserts</a></li>
                            <li><a asp-action="Index" asp-controller="Fries"><i class="fa fa-circle-o"></i> Fries</a></li>
                            <li><a asp-action="Index" asp-controller="Sauce"><i class="fa fa-circle-o"></i> Sauces</a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-laptop"></i>
                            <span>Orders</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a onclick="OrderList()"><i class="fa fa-circle-o"></i> List</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="/User/UserHome/Index">
                            <i class="fa fa-home"></i> <span>User Mode</span>
                        </a>
                    </li>

                    <li>
                            <a asp-action="LogOut" asp-controller="AdminHome">
                            <i class="fa fa-share"></i><span>Log out </span><span class="text-danger">@User.Identity.Name</span>
                            </a>                    
                    </li>

                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

    </div>

    <div>
        <div class="content-wrapper">
            <div style="margin-left:100px;margin-right:100px">
                <div style="padding-top:30px">
                    @RenderBody()
                </div>
                
            </div>
            
        </div>        
    </div>
    <script src="~/Content/plugins/jQuery/jQuery-2.1.3.min.js"></script>
    <!-- jQuery UI 1.11.2 -->
    <script src="http://code.jquery.com/ui/1.11.2/jquery-ui.min.js" type="text/javascript"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="~/Content/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- Morris.js charts -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="~/Content/plugins/morris/morris.min.js" type="text/javascript"></script>
    <!-- Sparkline -->
    <script src="~/Content/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
    <!-- jvectormap -->
    <script src="~/Content/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
    <script src="~/Content/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/Content/plugins/knob/jquery.knob.js" type="text/javascript"></script>
    <!-- daterangepicker -->
    <script src="~/Content/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
    <!-- datepicker -->
    <script src="~/Content/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="~/Content/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="~/Content/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <!-- Slimscroll -->
    <script src="~/Content/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='~/Content/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/app.min.js" type="text/javascript"></script>

    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Content/dist/js/pages/dashboard.js" type="text/javascript"></script>

    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/dist/js/demo.js" type="text/javascript"></script>

    <script src="/js/site.js"></script>


</body>
</html>