HamburgerMenuProject/Models/Entities/Menu.cs
using HamburgerMenuProject.Models.BaseEntities;

namespace HamburgerMenuProject.Models.Entities
{
    public class Menu : BaseEntity
    {
        public ICollection<Hamburger> Hamburgers { get; set; }
        public ICollection<Drink> Drinks { get; set; }
        public ICollection<Fries> Fries { get; set; }
        public ICollection<Dessert> Desserts { get; set; }
        public ICollection<Sauce> Sauces { get; set; }

        public Menu()
        {
            Hamburgers = new HashSet<Hamburger>();
            Drinks = new HashSet<Drink>();
            Fries = new HashSet<Fries>();
            Desserts = new HashSet<Dessert>();
            Sauces = new HashSet<Sauce>(); 
        }
    }
}

HamburgerMenuProject/Areas/User/Controllers/UserHomeController.cs
using HamburgerMenuProject.Models;
using HamburgerMenuProject.Models.BaseEntities;
using HamburgerMenuProject.Models.Entities;
using HamburgerMenuProject.Models.User;
using HamburgerMenuProject.Repository.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using System.Collections;
using System.Diagnostics;
using System.Xml.Linq;

namespace HamburgerMenuProject.Controllers
{
    public class UserHomeController : Controller
    {
        private readonly ILogger<UserHomeController> _logger;
        private readonly IRepository<Hamburger> hamburgerRepository;
        private readonly IRepository<Fries> friesRepository;
        private readonly IRepository<Dessert> dessertRepository;
        private readonly IRepository<Drink> drinkRepository;
        private readonly IRepository<Sauce> sauceRepository;
        private readonly IRepository<Menu> menuRepository;
        private readonly IRepository<Order> orderRepository;
        private readonly UserManager<AppUser> userManager;
        private readonly IOrderRepository orderRepo;

        public UserHomeController(ILogger<UserHomeController> logger, IRepository<Hamburger> hamburgerRepository, IRepository<Fries> friesRepository, IRepository<Dessert> dessertRepository, IRepository<Drink> drinkRepository, IRepository<Sauce> sauceRepository, IRepository<Menu> menuRepository, IRepository<Order> orderRepository, UserManager<AppUser> userManager, IOrderRepository orderRepo)
        {
            _logger = logger;
            this.hamburgerRepository = hamburgerRepository;
            this.friesRepository = friesRepository;
            this.dessertRepository = dessertRepository;
            this.drinkRepository = drinkRepository;
            this.sauceRepository = sauceRepository;
            this.menuRepository = menuRepository;
            this.orderRepository = orderRepository;
            this.userManager = userManager;
            this.orderRepo = orderRepo;
        }

        public static Order order = new();
        [AllowAnonymous]
        public IActionResult Index()
        {            
            int count = 0;
            foreach (var item in order.Hamburgers)
            {
                count += item.Piece;
            }
            foreach (var item in order.Fries)
            {
                count += item.Piece;

            }
            foreach (var item in order.Desserts)
            {
                count += item.Piece;

            }
            foreach (var item in order.Menus)
            {                
                count += item.Piece;

            }
            foreach (var item in order.Sauces)
            {                
                count += item.Piece;

            }
            foreach (var item in order.Drinks)
            {                
                count += item.Piece;

            }
            ViewBag.ItemCount = count;
            return View();
        }
        [AllowAnonymous]
        public IActionResult Menus()
        {
            var hamburgerList = hamburgerRepository.GetAll().ToList();
            var dessertList = dessertRepository.GetAll().ToList();
            var drinkList = drinkRepository.GetAll().ToList();
            var friesList = friesRepository.GetAll().ToList();
            var sauceList = sauceRepository.GetAll().ToList();
            var menuList = menuRepository.GetAll().ToList();
            FoodListVM foodListVM = new();
            foodListVM.Hamburgers = hamburgerList;
            foodListVM.Desserts = dessertList;
            foodListVM.Drinks = drinkList;
            foodListVM.Fries = friesList;
            foodListVM.Sauces = sauceList;
            foodListVM.Menus = menuList;
            int count = 0;
            foreach (var item in order.Hamburgers)
            {
                count += item.Piece;
            }
            foreach (var item in order.Fries)
            {
                count += item.Piece;

            }
            foreach (var item in order.Desserts)
            {
                count += item.Piece;

            }
            foreach (var item in order.Menus)
            {
                count += item.Piece;

            }
            foreach (var item in order.Sauces)
            {
                count += item.Piece;

            }
            foreach (var item in order.Drinks)
            {
                count += item.Piece;

            }
            ViewBag.ItemCount = count;
            return View(foodListVM);
        }
        [AllowAnonymous]
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult UserLogin()
        {
            return View();
        }
        public IActionResult SendMessage()
        {
            return PartialView("_SendMessage");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
        
        public async Task<IActionResult> SaveOrder()
        {
            AppUser user = await userManager.GetUserAsync(HttpContext.User);
            Order saveOrder = new();
            saveOrder.UserId = user.Id;
            order.UserId = user.Id;
            orderRepository.Add(saveOrder);
            order.ID = saveOrder.ID;
            saveOrder = order;
            orderRepo.UpdateMethod(saveOrder);            
            
            
            order.Menus.Clear();
            order.Hamburgers.Clear();
            order.Drinks.Clear();
            order.Desserts.Clear();
            order.Fries.Clear();
            order.Sauces.Clear();
            return RedirectToAction("Menus");
        }

        public IActionResult ShoppingCart()
        {
            if (order != null)
            {
                decimal total = 0;
                int count = 0;
                foreach (var item in order.Hamburgers)
                {
                    total += (decimal)item.Price * item.Piece;
                    count += item.Piece;
                }
                foreach (var item in order.Fries)
                {
                    total += (decimal)item.Price * item.Piece;
                    count += item.Piece;

                }
                foreach (var item in order.Desserts)
                {
                    total += (decimal)item.Price * item.Piece;
                    count += item.Piece;

                }
                foreach (var item in order.Menus)
                {
                    total += (decimal)item.Price * item.Piece;
                    count += item.Piece;

                }
                foreach (var item in order.Sauces)
                {
                    total += (decimal)item.Price * item.Piece;
                    count += item.Piece;

                }
                foreach (var item in order.Drinks)
                {
                    total += (decimal)item.Price * item.Piece;
                    count += item.Piece;

                }
                ViewBag.TotalPrice = total;
                ViewBag.ItemCount = count;
                order.Price=total;
            }
            
            return View(order);
        }

        public IActionResult AddShoppingCart(int id,string name)
        {
            switch (name)
            {
                case "hamburger":
                    var hamburger = hamburgerRepository.GetById(id);
                    var forHamList = order.Hamburgers.Where(x => x.ID == id).FirstOrDefault();                    
                    if (order.Hamburgers.Contains(forHamList))
                    {
                        forHamList.Piece++;
                        decimal defHamPrice = (decimal)hamburgerRepository.GetById(id).Price;
                        hamburger.Price = defHamPrice*hamburger.Piece;
                    }
                    else
                    {
                        order.Hamburgers.Add(hamburger);
                    }                    
                    break;

                case "fries":
                    var fries = friesRepository.GetById(id);
                    var forFriesList = order.Fries.Where(x => x.ID == id).FirstOrDefault();
                    if (order.Fries.Contains(forFriesList))
                    {
                        forFriesList.Piece++;
                        decimal defFriesPrice = (decimal)friesRepository.GetById(id).Price;
                        fries.Price = defFriesPrice*fries.Piece;
                    }
                    else
                    {
                        order.Fries.Add(fries);
                    }                    
                    break;

                case "drink":
                    var drink = drinkRepository.GetById(id);
                    var forDrinkList = order.Drinks.Where(x => x.ID == id).FirstOrDefault();
                    if (order.Drinks.Contains(forDrinkList))
                    {
                        forDrinkList.Piece++;
                        decimal defDrinkPrice = (decimal)drinkRepository.GetById(id).Price;
                        drink.Price = defDrinkPrice * drink.Piece;
                    }
                    else
                    {
                        order.Drinks.Add(drink);
                    }
                    break;

                case "dessert":
                    var dessert = dessertRepository.GetById(id);
                    var forDessertList = order.Desserts.Where(x => x.ID == id).FirstOrDefault();
                    if (order.Desserts.Contains(forDessertList))
                    {
                        forDessertList.Piece++;

HamburgerMenuProject/Areas/User/Views/UserHome/About.cshtml
@{
    ViewBag.Title = "AboutUs";
    Layout = "~/Areas/User/Views/Shared/_UserLayout.cshtml";
}
<main id="main-container" class="main-container">
    <div class="about-top">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="about-img">
                        <div class="img-responsive">
                            <img src="/images/client1.jpg" />
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="about-content">
                        <h4 class="font--regular">We Are A Gsore Focused On Delivering Best Organic Food And User Experiences.</h4>
                        <p class="para__text">
                            Burgers and fries. It’s a decidedly simple concept on the surface. But try an FakeDonald and you are struck by the taste of burger perfection.

                            Since opening in Fall 2008, FakeDonald has developed a devoted following of Triangle food lovers, first drawn to their mobile burger truck and now to their Shannon Road restaurant in Durham. The FakeDonald truck is the poster child for the exploding Durham mobile food scene and continues to roam the streets, strategically positioned throughout the Triangle for hungry diners at all hours of the day and night. A loyal following on social networking sites like Twitter feeds diners with location, information and burgers. Since it’s impossible to be at the right place at all times, FakeDonald opened the restaurant in November of 2010 to keep up with increasing demand.

                            Simply put, FakeDonald is obsessed with creating the perfect burger. With 25 years of fine dining restaurant and catering experience, owner Brian Bottger believes even “regular” food becomes extraordinary when executed at a high level. Triangle diners agree, voting FakeDonald Best Burger in Durham County, Best Food Truck in the Triangle and Best Fries in the Triangle in The Independent Weekly ’11, ’12, and ’13 Readers’ Choice Awards.

                            FakeDonald’s chef-driven approach to a mass appeal food is a key to FakeDonald’s success. Bottger boasts a long career in fine dining, having worked front of house in Enoteca Vin, Pop’s, Nana’s, and Il Palio in the Triangle as well as Wente Brothers Sparkling Wine Cellar & Restaurant in Livermore, CA.

                            This experience in food and a dedication to using only the finest ingredients can be tasted in every bite at FakeDonald. Burgers are made fresh to order, and fries are hand cut fresh daily. No corners are cut to deliver the finest burger to FakeDonald diners.

                            With recent stories in the New York Times, Durham Magazine, Martha Stewart Living and the Raleigh News & Observer and its recent runner-up finish in the national America’s Favorite Food Truck Giveaway on The Food Network, FakeDonald is poised for greater things in the years to come.

                            FakeDonald…when only the best will do!
                        </p>                        
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- ::::::  Start CMS Section  ::::::  -->
    <div class="cms m-t-100">
        <div class="container">
            <div class="row">
                <!-- Start Single CMS box -->
                <div class="col-lg-4 col-md-6 col-12">
                    <div class="cms__content">
                        <div class="cms__icon">
                            <i class="fas fa-truck"></i>
                        </div>
                        <div class="cms__text">
                            <h6 class="cms__title">Free Shipping</h6>
                            <p class="para__text">Free Shipping availabe at home.</p>
                        </div>
                    </div>
                </div> <!-- End Single CMS box -->
                <!-- Start Single CMS box -->
                <div class="col-lg-4 col-md-6 col-12">
                    <div class="cms__content">
                        <div class="cms__icon">
                            <i class="far fa-money-bill-alt"></i>
                        </div>
                        <div class="cms__text">
                            <h6 class="cms__title">100% Money Back Guarantee</h6>
                            <p class="para__text">Online Fresh Food will be back</p>
                        </div>
                    </div>
                </div> <!-- End Single CMS box -->
                <!-- Start Single CMS box -->
                <div class="col-lg-4 col-md-6 col-12">
                    <div class="cms__content">
                        <div class="cms__icon">
                            <i class="far fa-life-ring"></i>
                        </div>
                        <div class="cms__text">
                            <h6 class="cms__title">Online Support 24/7</h6>
                            <p class="para__text">24/7 online support</p>
                        </div>
                    </div>
                </div> <!-- End Single CMS box -->
            </div>
        </div>
    </div> <!-- ::::::  End CMS Section  ::::::  -->
</main>

HamburgerMenuProject/Areas/User/Views/UserHome/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/User/Views/Shared/_UserLayout.cshtml";
}
<div style="margin-top:50px" id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="/images/carousel-1.jpg" alt="First slide" height="600px">
            <div class="carousel-caption d-none d-md-block">
                <h5 style="font-weight: bold;">DELICIOUS'</h5>
                <p style="font-weight: bold;">We prepare all hamburgers with delicious taste</p>
            </div>
    </div>
    <div class="carousel-item">
            <img class="d-block w-100" src="/images/carousel-2.jpg" height="600px" alt="Second slide">
            <div class="carousel-caption d-none d-md-block">
                <h5 style="font-weight: bold;">LOVE</h5>
                <p style="font-weight: bold;">We present our hamburgers with our love</p>
            </div>
    </div>
    <div class="carousel-item">
            <img class="d-block w-100" src="/images/carousel-3.jpg" height="600px" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
                <h5 style="font-weight: bold;">HYGIENE</h5>
                <p style="font-weight: bold;">Hygiene is very important to us</p>
            </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

HamburgerMenuProject/Areas/User/Views/UserHome/Menus.cshtml
@using HamburgerMenuProject.Models;
@model FoodListVM
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/User/Views/Shared/_UserLayout.cshtml";
}


<style>
    .product-grid {
        background-color: #fff;
        font-family: 'Montserrat', sans-serif;
        text-align: center;
    }

        .product-grid .product-image {
            overflow: hidden;
            position: relative;
        }

            .product-grid .product-image a.image {
                display: block;
            }

            .product-grid .product-image img {
                width: 230px;
                height: 230px;
            }

            .product-grid .product-image .pic-1 {
                transition: all 0.3s ease 0s;
            }

            .product-grid .product-image:hover .pic-1 {
                transform: translateX(100%);
            }

            .product-grid .product-image .pic-2 {
                width: 230px;
                height: 230px;
                transform: translateX(-100%);
                position: absolute;
                top: 0;
                left: 0;
                transition: all 0.3s ease 0s;
            }

            .product-grid .product-image:hover .pic-2 {
                transform: translateX(0);
            }

        .product-grid .product-sale-label {
            color: #fff;
            background: #0a805e;
            font-size: 13px;
            text-transform: uppercase;
            letter-spacing: 1px;
            padding: 2px 8px;
            position: absolute;
            top: 15px;
            left: 15px;
        }

        .product-grid .product-like-icon {
            color: #696969;
            font-size: 22px;
            line-height: 20px;
            position: absolute;
            top: 15px;
            right: 15px;
        }

            .product-grid .product-like-icon:hover {
                color: #0a805e;
            }

            .product-grid .product-like-icon:before,
            .product-grid .product-like-icon:after {
                content: attr(data-tip);
                color: #fff;
                background-color: #000;
                font-size: 12px;
                line-height: 18px;
                padding: 7px 7px 5px;
                visibility: hidden;
                position: absolute;
                right: 0;
                top: 15px;
                transition: all 0.3s ease 0s;
            }

            .product-grid .product-like-icon:after {
                content: '';
                height: 15px;
                width: 15px;
                padding: 0;
                transform: translateX(-50%) rotate(45deg);
                right: auto;
                left: 50%;
                top: 15px;
                z-index: -1;
            }

            .product-grid .product-like-icon:hover:before,
            .product-grid .product-like-icon:hover:after {
                visibility: visible;
                top: 30px;
            }

        .product-grid .product-links {
            width: 170px;
            padding: 0;
            margin: 0;
            list-style: none;
            opacity: 0;
            transform: translateX(-50%);
            position: absolute;
            bottom: -50px;
            left: 50%;
            transition: all 0.3s ease 0s;
        }

        .product-grid:hover .product-links {
            bottom: 40px;
            opacity: 1;
        }

        .product-grid .product-links li {
            display: inline-block;
            margin: 0 2px;
        }

            .product-grid .product-links li a {
                color: #fff;
                background: #000;
                font-size: 16px;
                line-height: 48px;
                width: 48px;
                height: 48px;
                border-radius: 10px;
                display: block;
                transition: all 0.3s ease 0s;
            }

        .product-grid:hover .product-links li a:hover {
            background: #333;
        }

        .product-grid .product-content {
            text-align: left;
            padding: 15px 0 0;
        }

        .product-grid .title {
            font-size: 14px;
            font-weight: 500;
            text-transform: capitalize;
            margin: 0 0 8px;
        }

            .product-grid .title a {
                color: #333;
                transition: all 0.3s ease 0s;
            }

                .product-grid .title a:hover {
                    color: #0a805e;
                }

        .product-grid .price {
            color: #0a805e;
            font-size: 16px;
            font-weight: 500;
        }

            .product-grid .price span {
                color: #555;
                font-size: 14px;
                font-weight: 400;
                text-decoration: line-through;
                margin: 0 5px 0 0;
            }

</style>

<div class="row">
    @foreach (var item in Model.Menus)
    {
        if (item.IsActive)
        {
            <div style="padding:30px" class="col-md-3 col-sm-6">
                <div class="product-grid">
                    <div class="product-image">
                        <a href="#" class="image">
                            <img class="pic-1" src="/images/@item.Photo">
                            <img class="pic-2" src="/images/@item.Photo">
                        </a>
                        <ul class="product-links">
                            <li><a asp-action="AddShoppingCart" asp-controller="UserHome" asp-route-id="@item.ID" asp-route-name="menu"><i class="fas fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="product-content">
                        <h3 class="title"><a href="#">@item.Name</a></h3>
                        <div class="price">$@item.Price</div>
                    </div>
                </div>
            </div>
        }
    }
    @foreach (var item in Model.Hamburgers)
    {
        if (item.IsActive)
        {
            <div style="padding:30px" class="col-md-3 col-sm-6">
                <div class="product-grid">
                    <div class="product-image">
                        <a href="#" class="image">
                            <img class="pic-1" src="/images/@item.Photo">
                            <img class="pic-2" src="/images/@item.Photo">
                        </a>
                        <ul class="product-links">
                            <li><a asp-action="AddShoppingCart" asp-controller="UserHome" asp-route-id="@item.ID" asp-route-name="hamburger"><i class="fas fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="product-content">
                        <h3 class="title"><a href="#">@item.Name</a></h3>
                        <div class="price">$@item.Price</div>
                    </div>
                </div>
            </div>
        }

    }
    @foreach (var item in Model.Desserts)
    {
        if (item.IsActive)
        {
            <div style="padding:30px" class="col-md-3 col-sm-6">
                <div class="product-grid">
                    <div class="product-image">
                        <a href="#" class="image">
                            <img class="pic-1" src="/images/@item.Photo">
                            <img class="pic-2" src="/images/@item.Photo">
                        </a>
                        <ul class="product-links">
                            <li><a asp-action="AddShoppingCart" asp-controller="UserHome" asp-route-id="@item.ID" asp-route-name="dessert"><i class="fas fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="product-content">
                        <h3 class="title"><a href="#">@item.Name</a></h3>
                        <div class="price">$@item.Price</div>
                    </div>
                </div>
            </div>
        }

    }
    @foreach (var item in Model.Drinks)
    {
        if (item.IsActive)
        {
            <div style="padding:30px" class="col-md-3 col-sm-6">
                <div class="product-grid">
                    <div class="product-image">
                        <a href="#" class="image">
                            <img class="pic-1" src="/images/@item.Photo">
                            <img class="pic-2" src="/images/@item.Photo">
                        </a>
                        <ul class="product-links">
                            <li><a asp-action="AddShoppingCart" asp-controller="UserHome" asp-route-id="@item.ID" asp-route-name="drink"><i class="fas fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="product-content">
                        <h3 class="title"><a href="#">@item.Name</a></h3>
                        <div class="price">$@item.Price</div>
                    </div>
                </div>
            </div>
        }

    }
    @foreach (var item in Model.Fries)
    {
        if (item.IsActive)
        {
            <div style="padding:30px" class="col-md-3 col-sm-6">
                <div class="product-grid">
                    <div class="product-image">
                        <a href="#" class="image">
                            <img class="pic-1" src="/images/@item.Photo">
                            <img class="pic-2" src="/images/@item.Photo">
                        </a>
                        <ul class="product-links">
                            <li><a asp-action="AddShoppingCart" asp-controller="UserHome" asp-route-id="@item.ID" asp-route-name="fries"><i class="fas fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="product-content">
                        <h3 class="title"><a href="#">@item.Name</a></h3>
                        <div class="price">$@item.Price</div>
                    </div>
                </div>
            </div>
        }

    }
    @foreach (var item in Model.Sauces)
    {
        if (item.IsActive)
        {
            <div style="padding:30px" class="col-md-3 col-sm-6">
                <div class="product-grid">
                    <div class="product-image">
                        <a href="#" class="image">
                            <img class="pic-1" src="/images/@item.Photo">
                            <img class="pic-2" src="/images/@item.Photo">
                        </a>
                        <ul class="product-links">
                            <li><a asp-action="AddShoppingCart" asp-controller="UserHome" asp-route-id="@item.ID" asp-route-name="sauce"><i class="fas fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="product-content">
                        <h3 class="title"><a href="#">@item.Name</a></h3>
                        <div class="price">$@item.Price</div>
                    </div>
                </div>
            </div>
        }

    }

</div>

HamburgerMenuProject/Areas/User/Views/UserHome/_SendMessage.cshtml
<h3>Sent Successfully</h3>
@section Scripts {
@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}